---
title: "Elexon Data test"
format: html
---

## packages

```{r include=FALSE}
require(tidyverse)
require(kableExtra)
require(parallel)
require(dplyr)
require(scales)
require(ggsci)

require(jsonlite)
require(httr)

require(data.table)
require(sf)
library(rnaturalearth)
library(rnaturalearthdata)

require(plotly)
require(ggthemes)

```
## Data paths

```{r}
path <- "data"
```

```{r}
source("aux_funct.R")
```
## Catalog REPD


```{r}
# list.files(file.path(path), pattern = "repd")
repd0 <- fread(file.path(path,"repd-q2-jul-2025.csv")) %>% 
    rename(
    tech_typ = `Technology Type`,
    devel_stat = `Development Status (short)`,
    capacity_repd = `Installed Capacity (MWelec)`,
    capacity_turb = `Turbine Capacity`,
    n_turb = `No. of Turbines`,
    height_turb = `Height of Turbines (m)`,
    x_coord = `X-coordinate`,
    y_coord = `Y-coordinate`)
names(repd0) <- tolower(gsub(" ", "_", names(repd0)))
# filter wind only
# repd0$tech_typ |> unique()

repd_wind <- repd0 %>% 
  filter(
    tech_typ %in% c("Wind Onshore", "Wind Offshore"),
    # devel_stat %in% c("Operational")
    ) %>% 
#   mutate(
#     site_name = stringi::stri_enc_toutf8(as.character(site_name)),
#     tech_typ  = stringi::stri_enc_toutf8(as.character(tech_typ))
#   )
    mutate(
    site_name = iconv(site_name, from = "latin1", to = "UTF-8"),
    site_name = gsub("[^[:print:]]", "", site_name),
    ref_id = as.character(ref_id)
  )
```

```{r}
repd0 %>% filter(
    # tech_typ %in% c("Wind Onshore", "Wind Offshore", "Solar"),
    grepl("Wind", tech_typ),
    devel_stat %in% c("Operational", "Under Construction")
    ) %>% 
    group_by(tech_typ, devel_stat) %>% 
    summarise(
      n = n_distinct(ref_id),
      capacity = sum(capacity_repd, na.rm = TRUE)
    ) %>% 
    janitor::adorn_totals(where = "row") %>% 
    kable(
      col.names = c("Type", "Development Status","Count","Capacity MW"),
      digits =0,
      format.args = list(big.mark = ","))
```

### plot wind farms

```{r}
uk_ie <- ne_countries(scale = "medium", returnclass = "sf") %>%
  filter(admin %in% c("United Kingdom", "Ireland")) %>%
  st_transform(crs = 4326)

repd_p <- repd_wind %>% 
  filter(!is.na(x_coord), x_coord != "") %>% 
  filter(devel_stat == "Operational") %>% 
  st_as_sf(coords = c("x_coord","y_coord"), crs = 27700) %>% 
   st_transform(4326) %>% 
  ggplot()+
  geom_sf(data = uk_ie, fill = "gray95", color = "gray70") +  # map background
  geom_sf(aes(
    geometry = geometry, 
    col = tech_typ, 
    text = paste("Site:", site_name, "<br>Tech:", tech_typ)),
    # size = 1
    alpha = 0.2
    )+
  coord_sf(datum = 4326, crs = 4326)+
  scale_color_manual(values = pal_aaas()(3))+
  theme_map()+
  labs(col = "")+ theme(legend.position = "bottom")

plotly::ggplotly(repd_p, tooltip = "text")

```

## add catalog with BMU codes
```{r}
id_catalog <- readxl::read_xlsx(
  path = file.path(path,"osuked","id_dictionary.xlsx"),
  na = c("NA", "n/a", "-","")
) %>% 
   rename(
    rep_id = `REPD ID (New)`,
    bmu_id = `Settlement BMU ID`,
    dict_id = `Dictionary ID`,
    name = `Common Name`
    ) %>%
    filter(!is.na(rep_id)) %>% 
    mutate(dict_id = as.character(dict_id))
names(id_catalog) <- tolower(gsub(" ", "_", names(id_catalog)))
bmu_to_repd <- id_catalog %>% 
  separate_rows(bmu_id, sep = ",\\s*") %>%
  separate_rows(rep_id, sep = ",\\s*") %>%
  select(dict_id, name, bmu_id, rep_id) %>% 
  unique()
# bmu_to_dict %>% head()
```

```{r}
bmu_to_repd <- id_catalog %>% 
    # fix aikengall
    mutate(rep_id = ifelse(rep_id == "7015","4332, 4591", rep_id)) %>%
    # fix clyde wind farm: combine central and south / north: extension
    mutate(rep_id = ifelse(rep_id == "4011, 4178", "4011, 4178, 4011",rep_id ) ) %>% 
    # fix london array, all bmus to 2511, 2507 was abandoned
    mutate(rep_id = ifelse(rep_id == "2511, 2507", paste0(rep("2511",4), collapse = ", "), rep_id)) %>% 
    # fix thanet. only THNTO are active
    mutate(rep_id = ifelse(rep_id == "6299, 2499", "2499, 2499, 6299, 6299", rep_id)) %>% 
    # fix walney: last id covers 2 BMUs  2500, 2506, 2533, 2533
    mutate(
        rep_id = ifelse(rep_id == "2533, 2500, 2506", "2500, 2506, 2533, 2533", rep_id),
        bmu_id = ifelse(
            bmu_id == "T_WLNYW-1, E_WLNYW-2, T_WLNYO-3, T_WLNYO-4, T_WLNYO-2",
            "T_WLNYW-1, T_WLNYO-2, T_WLNYO-3, T_WLNYO-4",
            bmu_id)
            ) %>%
    # fix east anglia: EA1 and EA2 share BMUs
    mutate(rep_id = ifelse(rep_id == "2484, 6483, 2525, 2470", "2524, 2524", rep_id)) %>% 
    # fix hornsea 1
    mutate(rep_id = ifelse(rep_id == "2502, 2472, 2525", "2525, 2525, 2525", rep_id)) %>%
    # add hornsea 2
    bind_rows(
        data.frame(
            dict_id = "HORSEA2",
            name = "Hornsea 2",
            bmu_id = c("T_HOWBO-1","T_HOWBO-2","T_HOWBO-3"),
            rep_id = c("2502","2502","2502")
        )
    ) %>% 
    # fix clashindarroch
    mutate(rep_id = ifelse(rep_id == "3104", "4623", rep_id)) %>%
    # fix moray east
    mutate(rep_id = ifelse(rep_id == "2537", "2534", rep_id)) %>%
    # fix dorenell
    mutate(rep_id = ifelse(rep_id == "4244, 5051", "4244, 4244", rep_id)) %>%
    # add moray west 
    bind_rows(
        data.frame(
            dict_id = "MORAYWEST",
            name = "Moray West",
            bmu_id = c("T_MOWWO-1","T_MOWWO-2","T_MOWWO-3","T_MOWWO-4"),
            rep_id = c("6158")
        )
    ) %>% 
    # update sanquhar
    mutate(rep_id = ifelse(rep_id == "6629", "4441", rep_id)) %>%
    bind_rows(
        data.frame(
            dict_id = "Neart na Gaoithe",
            name = "Neart na Gaoithe",
            bmu_id = c("T_NNGAO-1","T_NNGAO-2"),
            rep_id = c("2522")
        )
    ) %>% 
    # fix burbo bank
    mutate(rep_id = ifelse(rep_id == "2539, 2487", "2487, 2539", rep_id )) %>% 
    mutate(across(c(bmu_id, rep_id),
                ~ str_split(.x, ",\\s*"))) %>%
  unnest(c(bmu_id, rep_id)) %>% 
  filter(
    rep_id != "6797",#fix berry burn
    rep_id != "3619" # fix beinneun
    )

bmu_to_repd <- bmu_to_repd 
```



```{r}
bmu_to_repd %>% 
  filter(!is.na(rep_id)) 
# ?readxl::read_xlsx
```

### elexon BMUs

#### elexon wind catalog
```{r}

url <- "https://data.elexon.co.uk/bmrs/api/v1/reference/bmunits/all"
response <- GET(url, accept("text/plain"))
json_data <- content(response, "text", encoding = "UTF-8")
bmus <- fromJSON(json_data) 
wind.bmus <- bmus %>% 
  filter(
    grepl("WIND",fuelType) | 
      grepl("wind|offshore", leadPartyName, ignore.case = TRUE )|
      grepl("wind farm|windfarm", bmUnitName, ignore.case = TRUE )) %>% 
  filter(!is.na(elexonBmUnit)) %>% 
  mutate(generationCapacity = as.numeric(generationCapacity))
# wind.bmus
```

```{r}
wind.bmus %>% 
  write.csv(
    .,gzfile(file.path("data", "wind_bmu_2.csv.gz"))
  )
```

#### BMUS with data 2025
```{r}
bmu_df <- fread(
  file.path(path,"data_by_year","wind_gen_bmu_2025.csv.gz")
)
bmu_25 <- bmu_df %>% 
  group_by(bmUnit) %>% 
  summarise(quantity = mean(quantity, na.rm = TRUE)) %>% 
  arrange(desc(quantity))

```

```{r}
bmu_df <- fread(
  file.path(path,"data_by_year","wind_gen_bmu_2025.csv.gz")
)
bmu_hours <- bmu_df %>% 
  group_by(bmUnit) %>% arrange(halfHourEndTime) %>% 
  mutate(quantity = quantity + lag(quantity)) %>% 
  filter(minute(halfHourEndTime) == 0) %>% 
  group_by(bmUnit) %>% 
  summarise(
    quantity_raw = sum(quantity, na.rm = TRUE),
    n_hours = n_distinct(halfHourEndTime)
    )

bmu_y <- bmu_df %>% 
  group_by(bmUnit) %>% arrange(halfHourEndTime) %>% 
  mutate(quantity = quantity + lag(quantity)) %>% 
  filter(quantity>=0) %>% 
  filter(minute(halfHourEndTime) == 0) %>% 
  group_by(bmUnit) %>% 
  summarise(
    quantity = sum(quantity, na.rm = TRUE),
    qpos_hours = n_distinct(halfHourEndTime)
    ) %>% 
  arrange(desc(quantity)) %>% 
  left_join(
    bmu_hours,
    by = "bmUnit"
  )
```

## add repd info
```{r}
repd_vars <- c("ref_id", "site_name", "tech_typ", "capacity_repd", "capacity_turb", "n_turb", "height_turb","devel_stat","x_coord","y_coord","operational")

ref_catalog_2025 <- bmu_y %>%
    left_join(
    # wind bmus from elexon
        wind.bmus %>% select(
            elexonBmUnit,
            matches("name|capacity")) %>% unique(), 
            by = c("bmUnit" = "elexonBmUnit")) %>%
    left_join(
    # mapping elexon to repd
        bmu_to_repd %>% 
            select(bmu_id, rep_id, name),
        by = c("bmUnit" = "bmu_id")) %>% 
    left_join(
    # repd
        repd_wind %>% 
            select(any_of(repd_vars)),
        by = c("rep_id" = "ref_id")) %>% 
    mutate(operational_date = as.Date(operational, format = "%d/%m/%Y")) %>% 
    filter(!is.na(x_coord))

write.csv(
    ref_catalog_2025,
    gzfile(file.path("data/ref_catalog_wind_2025.csv.gz")),
    row.names = FALSE
)

```


```{r}
test %>% 
    summarise(
        total_gen = sum(quantity, na.rm = TRUE),
        total_cap = sum(generationCapacity, na.rm = TRUE)
    )
```


## extra BMU downloads
```{r}
source("aux_funct.R")
bmugen0 <- get_bmugen(
  year = 2025,
  path = file.path(path,"data_by_year"),
  end_time = "2025-09-30"
  )
```

### Extra maps

```{r}
ref_catalog_2025 <- fread(
  file.path("data/ref_catalog_wind_2025.csv.gz")
)
```
```{r}
# on shore off shore distribution
ref_catalog_2025 %>% 
    group_by(tech_typ) %>%
    summarise(
        total_gen = sum(quantity, na.rm = TRUE)/1000,
        total_cap = sum(generationCapacity, na.rm = TRUE),
        n = n()
    ) %>% 
    janitor::adorn_totals("row") %>%
    mutate(
        cap_factor = total_gen / (total_cap * 8760)*1000
    ) %>% 
    kable(
        col.names = c("Type", "Generation (GWh)", "Capacity (MW)", "Number of BMUs", "Capacity Factor"),
        digits = c(1,1,0,1,2),
        format.args = list(big.mark = ",")) %>%
    kable_styling(full_width = FALSE)
```

```{r}
?kable
```

#### wind farm locations
```{r}
uk_ie <- ne_countries(scale = "medium", returnclass = "sf") %>%
  filter(admin %in% c("United Kingdom", "Ireland")) %>%
  st_transform(crs = 4326)

p1 <- ref_catalog_2025 %>% 
  filter(!is.na(x_coord)) %>% 
  st_as_sf(coords = c("x_coord","y_coord"), crs = 27700) %>% 
   st_transform(4326) %>% 
  ggplot()+
  geom_sf(data = uk_ie, fill = "gray95", color = "gray70") +  # map background
  geom_sf(aes(
    geometry = geometry, 
    col = tech_typ, 
    text = paste("Site:", site_name, "<br>Tech:", tech_typ)),
    # size = 1
    )+
#   coord_sf(datum = 4326, crs = 4326)+
  scale_color_manual(values = pal_aaas()(3))+
  labs(col = "")+
#   x = "Longitude (\u00B0E)", y = "Latitude (\u00B0N)")+
  theme(legend.position = "bottom")

p1
# ggsave(
#     filename = "fig/wind_farms_elexon_2025.eps",
#     plot = p1,
#     width = 4,
#     height = 6,
#     units = "in",
#     dpi = 300
# )
```

#### wind farm locations by capacity
```{r}
p1 <- ref_catalog_2025 %>% 
  filter(!is.na(x_coord)) %>% 
  st_as_sf(coords = c("x_coord","y_coord"), crs = 27700) %>% 
   st_transform(4326) %>% 
  ggplot()+
  geom_sf(data = uk_ie, fill = "gray95", color = "gray70") +  # map background
  geom_sf(aes(
    geometry = geometry, 
    col = tech_typ, 
    size = generationCapacity,
    text = paste("Site:", site_name, "<br>Tech:", tech_typ)),
    # size = 1
    alpha = 0.2
    )+
#   coord_sf(datum = 4326, crs = 4326)+
  scale_color_manual(values = mypalette)+
  labs(col = "", size = "capacity")+
#   x = "Longitude (\u00B0E)", y = "Latitude (\u00B0N)")+
theme_map()+
  theme(legend.position = "left")

p1
ggsave(
    filename = "fig/wind_farms_elexon_size_2025.jpeg",
    plot = p1,
    width = 4,
    height = 4,
    units = "in",
    dpi = 300
)
```
#### wind farm locations by generation
```{r}
p1 <- ref_catalog_2025 %>% 
  filter(!is.na(x_coord)) %>% 
  st_as_sf(coords = c("x_coord","y_coord"), crs = 27700) %>% 
   st_transform(4326) %>% 
  ggplot()+
  geom_sf(data = uk_ie, fill = "gray95", color = "gray70") +  # map background
  geom_sf(aes(
    geometry = geometry, 
    col = tech_typ, 
    size = quantity/1000,
    text = paste("Site:", site_name, "<br>Tech:", tech_typ)),
    # size = 1
    alpha = 0.2
    )+
#   coord_sf(datum = 4326, crs = 4326)+
  scale_color_manual(values = pal_aaas()(2) %>% rev())+
  labs(col = "", size = "generation")+
#   x = "Longitude (\u00B0E)", y = "Latitude (\u00B0N)")+
  theme_map()+
  theme(legend.position = "left")

p1
ggsave(
    filename = "fig/wind_farms_elexon_gen_2025.jpeg",
    plot = p1,
    width = 4,
    height = 6,
    units = "in",
    dpi = 300
)
```

```{r}

```
```{r}
ref_catalog_2025 %>% 
    pull(generationCapacity) %>% 
    summary()

ref_catalog_2025 %>% 
    ggplot()+
    geom_boxplot(aes(
        x= tech_typ,y = generationCapacity, fill = tech_typ
    ))+
    scale_fill_manual(values = pal_aaas()(2) %>% rev())+
    labs(
        x = "", y = "Capacity (MW)"
    )+
    theme_minimal(base_size = 14)+
    theme(legend.position = "none")

ggsave(
    filename = "fig/wind_capacity_box_2025.eps",
    width = 4,
    height = 4)
```

## Turbine exploratory analysis

```{r}
ref_catalog_2025 %>% 
    pull(height_turb) %>% 
    summary()

ref_catalog_2025 %>% 
    pull(n_turb) %>% 
    summary()

ref_catalog_2025 %>% 
    pull(capacity_turb) %>% 
    summary()
```

```{r}
ref_catalog_2025 %>% 
    ggplot()+
    geom_histogram(aes(capacity_turb, fill = tech_typ))+
    facet_wrap(~tech_typ)+
    scale_fill_manual(values = mypalette)+
    theme(legend.position = "none")+
    labs(x = "Turbine capacity MW")
ggsave(
    filename = "fig/hist_turb_capacity_2025.eps",
    width = 5,
    height = 4)
ref_catalog_2025 %>% 
    ggplot()+
    geom_histogram(aes(n_turb, fill = tech_typ))+
    facet_wrap(~tech_typ)+
    scale_fill_manual(values = mypalette)+
    theme(legend.position = "none")+
    labs(x = "Number of turbines")
ggsave(
    filename = "fig/hist_n_turb_2025.eps",
    width = 5,
    height = 4)

ref_catalog_2025 %>% 
    ggplot()+
    geom_histogram(aes(height_turb, fill = tech_typ))+
    facet_wrap(~tech_typ)+
    scale_fill_manual(values = mypalette)+
    theme(legend.position = "none")+
    labs(x = "Turbine height")
ggsave(
    filename = "fig/hist_turb_height_2025.eps",
    width = 5,
    height = 4)
```

```{r}
ref_catalog_2025 %>%
    mutate(operational_date = as.Date(operational, format = "%d/%m/%Y")) %>%
    pull(operational_date) %>% 
    summary()

# Compute cumulative capacity over time
capacity_time <- ref_catalog_2025 %>%
  mutate(operational_date = as.Date(operational, format = "%d/%m/%Y")) %>%
  arrange(operational_date) %>%
  mutate(cum_capacity = cumsum(generationCapacity))

# Plot
ggplot(capacity_time, aes(x = operational_date, y = cum_capacity)) +
  geom_line(color = "#0072B2", linewidth = 1) +
  labs(
    title = "Cumulative Installed Capacity Over Time",
    x = "Operational Date",
    y = "Cumulative Capacity (MW)"
  ) +
  theme_minimal(base_size = 14)


ggsave(
    filename = "fig/wind_capacity_2025.eps",
    width = 6,
    height = 4,
    units = "in",
    dpi = 300
)
```


```{r}
# Aggregate cumulative capacity by date and type
capacity_time <- ref_catalog_2025 %>%
  group_by(operational_date, tech_typ) %>%
  summarise(total_capacity = sum(generationCapacity, na.rm = TRUE), .groups = "drop") %>%
  arrange(operational_date) %>%
  group_by(tech_typ) %>%
  mutate(cum_capacity = cumsum(total_capacity)) %>%
  ungroup()

# 🔧 Create a complete grid of all dates and types
capacity_time_full <- capacity_time %>%
  complete(
    tech_typ,
    operational_date = seq(min(operational_date, na.rm =T), max(operational_date, na.rm =T), by = "day")
  ) %>%
  group_by(tech_typ) %>%
  fill(cum_capacity, .direction = "down") %>%  # carry last known value forward
  replace_na(list(cum_capacity = 0)) %>%       # fill before first commissioning
  ungroup()

capacity_p <- ggplot(capacity_time_full, aes(x = operational_date, y = cum_capacity, fill = tech_typ)) +
  geom_area( color = "white", linewidth = 0.3) +
#   scale_fill_manual(values = c("Wind Onshore" = "#66c2a5", "Wind Offshore" = "#fc8d62")) +
  scale_fill_manual(values = mypalette ) +
  labs(
    title = "Cumulative Wind Power Capacity",
    x = "Operational Date",
    y = "Cumulative Capacity (MW)",
    fill = "Type"
  ) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "top")

capacity_p
ggsave(
    filename = "fig/wind_capacity_type_2025.eps",
    width = 6,
    height = 4,
    units = "in",
    dpi = 300
)

ggsave(
  capacity_p + labs(title = ""),
    filename = "fig/wind_capacity_type_2025_nt.eps",
    width = 6,
    height = 4,
    units = "in",
    dpi = 300
)
```



```{r}
ref_catalog_2025$site_name %>% unique() %>% length()
```


## Testing curtailment function

```{r}
source("aux_funct.R")
path <- "~/Documents/elexon"
```


```{r}
bmucurt0 <- get_curtailment(
  year = 2025,
  path = file.path(path,"data_by_year"),
  end_time = "2025-09-30"
  )
```
```{r}
bmucurt0 %>% head()
```
```{r}
years <- 2022:2024

curt_df <- lapply(
  years,
  \(y) get_curtailment(
  year = y,
  path = file.path(path,"data_by_year")
  )
)

```


```{r}
bmucurt0 %>% 
  filter(dataType == "Tagged") %>% 
  group_by(settlementDate) %>% 
  summarise(curtailment = -sum(totalVolumeAccepted)) %>% 
  ggplot(aes(settlementDate, curtailment, group = 1))+
  geom_line()
```
```{r}
ref_catalog_2025 <- fread(
  file.path("data/ref_catalog_wind_2025.csv.gz")
)
uk_ie <- ne_countries(scale = "medium", returnclass = "sf") %>%
  filter(admin %in% c("United Kingdom", "Ireland")) %>%
  st_transform(crs = 4326)
p1 <- ref_catalog_2025 %>% 
  filter(!is.na(lon)) %>% 
  group_by(lon, lat, tech_typ) %>% 
  summarise(
    site_name = first(site_name),
    generationCapacity = sum(generationCapacity)) %>% 
  st_as_sf(coords = c("lon","lat"), crs = 4326) %>%
  ggplot()+
  geom_sf(data = uk_ie, fill = "gray95", color = "gray70") +  # map background
  geom_sf(aes(
    geometry = geometry, 
    col = tech_typ, 
    size = generationCapacity,
    text = paste("Site:", site_name, "<br>Tech:", tech_typ)),
    # size = 1
    alpha = 0.7
    )+
#   coord_sf(datum = 4326, crs = 4326)+
  scale_color_manual(values = mypalette)+
  labs(col = "", size = "capacity")+
#   x = "Longitude (\u00B0E)", y = "Latitude (\u00B0N)")+
theme_map()+
  theme(legend.position = "left")

p1
ggsave(
    filename = "fig/wind_farms_elexon_size_2025.pdf",
    plot = p1,
    width = 4,
    height = 4,
    units = "in",
    dpi = 300
)

```


